name: CI to Take Server
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SK }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd /home/ctkpaarr/website &&
            git fetch origin main &&
            git reset --hard origin/main &&
            pnpm i --no-frozen-lockfile &&
            pnpm run build &&
            echo 'build complete'
